### ISSUE TITLE
C analysis bug: sizeof(void *) is not the same as sizeof(void)

### ISSUE THREAD

**Issue by nickpelling** [baldapps/artemis#3]
When the "Sizeof applied to void type" option is selected, Artemis incorrectly flags this line as an error:

   *pxMailBox = xQueueCreate( iSize, sizeof( void * ) );

sizeof(void *) is not the same as sizeof(void).

PS: 2.5.0.202004151519

**Comment by baldapps** [comment]
Fixed with next version
