### ISSUE TITLE
C analysis: "For loop invariant" incorrectly emits warning if loop variable is used as an index in an array assignment

### ISSUE THREAD

**Issue by nickpelling** [baldapps/artemis#4]
With the "For loop invariant" option selected, Artemis incorrectly raises warnings on assignments where the loop variable is used as an array index (i.e. the loop variable is used as the index of the left hand side). Even the loop variable is used to calculate the destination address, it is not itself assigned to, so this is incorrect behaviour.

__STATIC_INLINE void ARM_MPU_OrderedMemcpy(volatile uint32_t* dst, const uint32_t* __RESTRICT src, uint32_t len)
{
  uint32_t i;
  for (i = 0U; i < len; ++i) 
  {
    dst[i] = src[i];
  }
}

PS: Artemis 2.5.0.202004151519

**Comment by baldapps** [comment]
Fixed with next version
